### ISSUE TITLE
Images from gatsby-image's fluid mode become stretched and include oversized span tag

### ISSUE THREAD

**Issue by me4502** [tomoyukikashiro/html2amp#137]
Hi,

I'm encountering an issue when using this via gatsby-plugin-html2amp (wasn't sure where to report it, decided here made more sense as gatsby-plugin-html2amp just bootstraps this).

It stretches out the image and leaves the blurred background behind it. On top of that, the original base64 from gatsby-image stays too and is stored in a span tag that ends up being larger than AMP spec allows for.

Here's an example broken page - https://matthewmiller.dev/amp/blog/worldedit-mod-blocks/

Running this through AMP test produces errors relating to the span tags in the responsive gatsby image wrapper. I feel that this whole wrapper can just be removed, but that doesn't fix the stretched image issue.
![image](https://user-images.githubusercontent.com/546754/82148015-05053d80-9895-11ea-8543-f3b58bbcae21.png)

**Comment by tomoyukikashiro** [comment]
Hi, @me4502 

gatsby-image is a react component which is not a drop-in replacement for `<img />`.
In your case the image is shown by using background-image on `span` tag.

This library is simple converter from HTML into AMP so that I would not support specific library issue.

But there is a solution. Library has plugin option which you can modify converted AMP.
https://github.com/tomoyukikashiro/html2amp#html-plugin

So you could solve this issue by replacing the `<span />` 👍
